### ISSUE TITLE
ユーザー登録フローの実装

### ISSUE THREAD

**Issue by soleil-colza** [Tech-SummerCamp/tomonhun#1]
- アカウント登録
- TwitterのOAuthで登録
- 好物の入力

アカウント情報としては、
- ID(Twitterのそのまま)
- 名前(初期値はIDと同一)
- 顔写真(Twitterアイコン)
- 好物
があればよさそう

**Comment by k-taro56** [comment]
やっぱりここは NextAuth.js を使うのがいいのでは？！

**Comment by Inlet-back** [comment]
@k-taro56  まず何からしたらいいですか。DB周りの環境構築ですか、それともいきなりnextAuth周りの実装できますか
