### ISSUE TITLE
シューティング画面の実装

### ISSUE THREAD

**Issue by soleil-colza** [Tech-SummerCamp/tomonhun#5]
- 友達のアバターを無作為な数、無作為な場所に浮かばせる
- タップで捕獲
- 断末魔を表示
- リザルトの表示 : 捕獲数と断末魔の一覧

**Comment by yuto-trd** [comment]
AR.js (three.js) 使いたい

- https://zenn.dev/drumath2237/articles/ea77b9ac60795e
  - ↑はマーカー型だけどロケーションベースつかう
  - https://ar-js-org.github.io/AR.js/#location-based-example
  - https://ar-js-org.github.io/AR.js-Docs/location-based/
- https://zenn.dev/hironorioka28/articles/5674b57278effd
- https://webar-lab.palanar.com/developer/threejs-markerless/
  - ↑Ar.jsで調べてたけど、なしでもいけそう
- https://aframe.io/docs/1.6.0/introduction/developing-with-threejs.html#

----
ロケーション使わない方向のほうが良さげ

**Comment by yuto-trd** [comment]
09-14 17:35
アバターの3dモデル待ちなので、シューティングのUI実装

**Comment by k-taro56** [comment]
残りの部分：#12

**Comment by k-taro56** [comment]
残りの部分：#12
